Cargo.toml
samples/configs/delta.yaml
src/commons/delta.rs
src/error.rs
src/errors/datafusion.rs
src/errors/deltalake.rs
src/errors/mod.rs
src/main.rs
src/tables/datafusion/mod.rs
src/tables/datafusion/predicates.rs
src/tables/datafusion/statistics.rs
src/tables/mod.rs
src/tables/polars/mod.rs
src/tables/polars/statistics.rs

This PR adds deltatable state managements using datafusion.

Add datafusion table

---

samples/configs/delta.yaml
src/computes/duckdb/mod.rs
src/configs.rs
src/servers/single/mod.rs
src/storages/delta/mod.rs

Add max_stats_batches to limit maximum batches for stats

Fix delta options

---

src/storages/delta/mod.rs

Use configure_log_store() instead of DefaultLogStore to create log store.

Use configure_log_store() instead of DefaultLogStore

---

Cargo.toml
src/commons/mod.rs
src/commons/tests.rs
src/configs.rs
src/state.rs
src/storages/delta/mod.rs

- tests #10 
Add test_predicates_pushdown() to test #10 issue.

Add unittests

---

Cargo.toml
examples/datafusion_query.rs
examples/flight_sql/Cargo.toml

Add sql query example using datafusion.

Add datafusion_query example

---

.gitignore
.vscode/settings.json

Add common json formatter settings for vscode

Add common json formatter settings

---

.vscode/settings.json
examples/delta_write.rs

Fix delta write

---

examples/delta_write.rs

Fix delta_write

---

src/storages/delta/mod.rs
src/storages/delta/statistics.rs

Add test_remove_action_stats() to test building statistics on remove actions.
- #10

Add unittest for buliding statistics on remove actions

---

src/commons/sql.rs

Add function supports to get_projection()

Add function supports to get_projection()

---

src/compute.rs
src/computes/duckdb/mod.rs
src/storage.rs
src/storages/delta/mod.rs
src/storages/delta/statistics.rs

Use schema reference for compute execution.

Use schema reference for compute execution

---

src/compute.rs
src/computes/duckdb/mod.rs
src/state.rs

Add table config to compute creation.

Add table config to compute creation

---

samples/configs/delta.yaml
src/storages/delta/mod.rs

Fix table location url parsing.

Fix table location parsing

---

src/computes/duckdb/mod.rs

Fix aws endpoint url parsing bugs

duckdb: Fix aws endpoint url bugs

---

src/storages/delta/mod.rs

Upgrade to latest version of deltalake crate.

Upgrade deltalake crate

---

src/main.rs
src/storages/delta/mod.rs

Register s3 schemes in delta storage factory

Register s3 schemes in delta storage factory

---

src/servers/single/mod.rs

Bypass authorization header if no authorization header.

Bypass authorization header

---

Cargo.toml

Upgrade to arrow 49

---

Cargo.toml

Upgrade to object store 0.8

---

src/table.rs

Add schema() to DQTable

---

src/commons/sql.rs

Fix no table bug

---

src/commons/sql.rs

Add value column supports

---

README.md

Fix LICENSE URL correctly in README file
NA
NA

Fix LICENSE URL correctly in README file

---

src/storages/delta/mod.rs
src/storages/delta/predicates.rs

- Cast date32/64 to utf8 type
- Ignore filter expressions which is not in statistics

Fix statistics filtering in delta storage

---

src/computes/duckdb/mod.rs
src/table.rs

Refactor table execution

---

src/commons/sql.rs

Add get_functions() to get all used user-defined functions from sql statements.

Add get_functions()

---

src/commons/sql.rs
src/storages/delta/mod.rs
src/table.rs

Refactor sqlparser

---

src/storages/delta/mod.rs

Sort filtered files by newest.

Sort filtered files by newest

---

src/commons/sql.rs

Use alias name instead of column name if has alias.

Add get_columns_with_alias()

---

src/commons/sql.rs
src/compute.rs

Add get_function_return_type() to compute engine.

Add get_function_return_type() to compute engine

---

src/table.rs

Add storage and compute execution time logs.

Add storage and compute execution time logs

---

Cargo.toml
src/errors/mod.rs
src/errors/tera.rs
src/storages/delta/mod.rs
src/storages/delta/predicates.rs
src/storages/delta/statistics.rs

Add datetime statistics using partition columns.

Add datetime statistics using partition columns

---

src/storages/delta/mod.rs
src/storages/delta/statistics.rs

Refactor timestamp statistics using partition columns.

Refactor timestamp statistics using partition columns

---

src/storages/delta/statistics.rs

Clean up get_record_batch_from_actions().

Clean up get_record_batch_from_actions()

---

src/servers/flightsql/single/mod.rs

Add no table query supports

---

src/compute.rs
src/computes/duckdb/mod.rs
src/main.rs
src/servers/flightsql/simple/mod.rs
src/servers/flightsql/single/mod.rs
src/state.rs

Refactor lock mechanisms for state, computes and tables.

Refactor lock mechanisms

---

src/tables/delta/mod.rs
src/tables/delta/statistics.rs

Fix add stats parsing bugs

---

src/state.rs
src/tables/delta/statistics.rs

Ignore add stats parsing errors.

Ignore add stats parsing errors

---

src/tables/delta/mod.rs
src/tables/delta/predicates.rs

Fix timestamp casting for predicates pushdown.

Fix timestamp casting for predicates pushdown

---

src/compute.rs
src/computes/duckdb/mod.rs

Add detail messages to compute errors.

Add detail messages to compute errors

---

src/compute.rs
src/computes/duckdb/mod.rs
src/state.rs
src/table.rs
src/tables/delta/mod.rs

Use try_new() instead of new().

Use try_new() instead of new()

---

src/tables/delta/mod.rs

Fix location trim bugs

---

src/state.rs

Add list functions for databases, schemas and tables.

Add list functions for databases, schemas and tables

---

Cargo.toml
src/commons/tests.rs

Don't use arrow backed table state.

Don't use arrow backed table state

---

src/table.rs
src/tables/delta/mod.rs

Add location() to table trait.

Add location() to table trait

---

samples/configs/delta.yaml
src/configs.rs
src/table.rs
src/tables/delta/mod.rs
src/tables/delta/statistics.rs

Use partition columns on delta's metadata.

Use partition columns on delta's metadata

---

src/configs.rs
src/lib.rs
src/metastore.rs
src/state.rs

Add metastore

---

src/compute.rs
src/computes/duckdb/mod.rs

Add schema() to compute trait.

Add schema() to compute trait

---

src/tables/delta/predicates.rs

Fix column name bugs in predicates.

Fix column name bugs in predicates

---

src/tables/delta/predicates.rs

Fix predicates bugs

---

src/tables/delta/predicates.rs

Fix number parsing in predicates.

Fix number parsing in predicates

---

src/table.rs
src/tables/delta/mod.rs

Add table_options supports to delta table.

Add table_options supports to delta table

---

src/tables/delta/mod.rs
src/tables/delta/statistics.rs

Fix statistics missing bugs

---

src/table.rs
src/tables/delta/mod.rs
src/tables/delta/predicates.rs

Refactor table filtering

---

Cargo.toml
src/lib.rs
src/signer.rs
src/signers/mod.rs
src/signers/s3.rs
src/table.rs
src/tables/delta/mod.rs

Add s3 signer

---

src/configs.rs

Add runtime config

---

src/compute.rs
src/computes/duckdb/mod.rs

Remove schema() from compute

---

Cargo.toml
src/configs.rs
src/tables/delta/mod.rs

Fix metastore schema

---

src/servers/flightsql/single/mod.rs

Add authentication supports

---

src/tables/delta/mod.rs

Remove deprecated functions

---

Cargo.toml
src/tables/delta/mod.rs

Upgrade arrow-datafusion

---

Cargo.toml
src/computes/mod.rs
src/main.rs

Add duckdb feature

---

src/configs.rs
src/state.rs
src/table.rs
src/tables/delta/mod.rs

Fix table configuration

---

src/tables/delta/mod.rs

Don't filter options for filesystems.

Don't filter options for filesystems
